version: '3.7'

services:
  drupal:
    image: drupal:8.8.1-apache
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
  database:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:


